---
all:
  children:
    prod:
      hosts:
        client
      vars:
        ansible_ssh_pass: centos
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
        env: production
  vars:
    ansible_user: centos
...

